### PR TITLE
Create encode-export-string.py

### PR DESCRIPTION
**Pull request by flameSla**

### CODE REVIEW

**Comment by asheiduk** [comment]
Thank you for your PR! I'll look into the code in the evening!

**Comment by asheiduk** [comment]
First of all: Thanks for you pull-request!

The `-e` option might be handy indeed. But your implementation is quite memory
intensive which affects larger blueprint libraries (think of ~160M or so which blows up to ~730MB compact JSON ). Thereason is that `json.dumps()` returns a huge string and every step after that
also uses much memory in the same ballpark.

This is also an issue with the other two scripts because `json.load` first
reads the complete file into an internal string instead doing efficient stream
processing.

NB: According to [Stackoverflow] doing streaming compression is not an easy,
"battery included" thing in Python :-(

[Stackoverflow]: https://stackoverflow.com/questions/2192529/python-creating-a-streaming-gzipd-file-like


**So**: I'd like to known what's the problem with the existing shell scripts?
AFAICT they DO stream processing and something like
`decode INPUT_FILE | encode-export-string > OUTPUT_FILE` would so the same as
your `decode -e INPUT_FILE > OUTPUT_FILE`.

**Comment by flameSla** [comment]
>So: I'd like to known what's the problem with the existing shell scripts?

I have Windows
I don't have jq and zlib-flate
it's easier for me to write everything in python :)

>The -e option might be handy indeed.

yeah, without intermediate files, my processing has become much faster
memory consumption is approximately 2.2 GB, the same as for Chrome

**Comment by asheiduk** [comment]
In the current state I won't merge the PR.

- The new Python scripts are not a drop-in replacement for the current shell
	scripts. This affects the `.py` extension, the missing `x` bits but most
	importantly they cannot be used in a pipeline. Instead of default filenames
	they should fall back to using STDIN/STDOUT. Error messages should go to
	STDERR. `decode-export-string` should exit with an error code and
	should not remove a file. Regarding the output format of that script:
	On one hand it uses `indent=1` (i.e. pretty printing) but uses the non standard
	`separators=(",", ":")` for compact output. The current script just decodes
	and does not pretty-print. I'm unsure about the best way.

- Since there will be no more `.py` extensions the `.gitignore` file should not
	be necessary any more.

- The new scripts and the actual `-e` option handle the JSON, base64
	and (de)compression in a very memory intensive way. I'd like to see some
	effort to reduce that footprint although for reading JSON there is actual
	no standard way.

- The `-e` option must be documented in the README. The long form should be
	a tad shorter. `--export-format` perhaps?
	
- The latest addition of `get_level.dat.py` are actually not ready for this
	repository. Although I'm curious in what direction you want to go with
	that :-)

**So**: I'd like to also add `-c/--compact-format` in addition to
`-e/--export-format`. Next week I might play around with these and will make
some attempts at using proper streams for output. Regarding the other two
script: Actually I don't feel pressure to include them right now.

Regarding streaming and memory: Today I've profiled my largest library (~160 MB `.dat`,
~1_914 MB pretty JSON) and found that the 21 million `dicts` alone are using
around 4_855 MB RAM (python 3.6.9). This dwarfs the memory for the complete
*compact* JSON (~725 MB) plus the compressed data (~46 MB) plus the base64
encoded data (~62 MB) plus the other copy of the base64 data with the `0`
prefix. So I might throw *some* brain to the streaming stuff but not to much.

**Comment by flameSla** [comment]
decoding the level.dat file is hopeless
we will have to write orders of magnitude more code than has already been written
and when new versions are released, you will have to change/check the code

**Comment by flameSla** [comment]
>On one hand it uses indent=1 (i.e. pretty printing) but uses the non standard
separators=(",", ":") for compact output. The current script just decodes
and does not pretty-print. I'm unsure about the best way.

the output format must be specified in the arguments: indent, etc.
decode-export-string.py --indent=10 --separator1=", " --separator2=": " < tests\win\bp.txt

**Comment by asheiduk** [comment]
I don't think a mere mortal user can do something sensible with these parameters. 

I thought, that `separators=(",", ":")` was just a copy&paste artefact. 
I see these options:

a) The script supports only compact format. Then `indent=` must be deleted.
b) The script supports only pretty format. Then `separators` must be deleted.
c) The script support both. In that case I propose the pretty format as the default (to be in line
 with `decode`) and an optional script parameter `-c/--compact-format`.

**Comment by flameSla** [comment]
imho, a fully customizable format is better, it is suitable for absolutely everyone
tomorrow I will want an indent = 10 and I will have to rewrite the sources

**Comment by asheiduk** [comment]
There are better tools to produce arbitrary JSON formats. Even Python itself support some of that:

https://docs.python.org/3/library/json.html#json-commandline

So: Piping the output from `decode-export-string` into one of those tools is essentially enough. Providing the `-c` format in *this* tools only has the benefit, that fewer bytes are produced which must be parsed by the next tool.

**Pull request closed without merging**
